/**
 * Copyright (c) Truveta. All rights reserved.
 */

/**
 * Represents the result of a token generation operation.
 *
 * This class contains the generated tokens, the list of invalid attributes,
 * and the count of blank tokens generated by rule.
 */
export class TokenGeneratorResult {
  /**
   * Map of generated tokens where keys are token identifiers (e.g., "T1", "T2")
   * and values are the generated token strings.
   *
   * Uses Map to maintain insertion order of token identifiers.
   */
  private readonly _tokens: Map<string, string> = new Map();

  /**
   * Set of attribute names that failed validation during token generation.
   *
   * Contains the names of attributes that were invalid and could not be
   * processed for token generation.
   */
  private readonly _invalidAttributes: Set<string> = new Set();

  /**
   * Set of token/rule identifiers that resulted in blank tokens.
   *
   * A blank token occurs when required attributes are missing or invalid,
   * preventing the generation of a valid token for that rule.
   */
  private readonly _blankTokensByRule: Set<string> = new Set();

  getTokens(): Map<string, string> {
    return this._tokens;
  }

  getInvalidAttributes(): Set<string> {
    return this._invalidAttributes;
  }

  getBlankTokensByRule(): Set<string> {
    return this._blankTokensByRule;
  }
}
