/**
 * Copyright (c) Truveta. All rights reserved.
 */
package com.truveta.opentoken.tokens;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import lombok.Getter;

/**
 * Represents the result of a token generation operation.
 * <p>
 * This class contains the generated tokens, the list of invalid attributes,
 * and the count of blank tokens generated by rule.
 * </p>
 */
@Getter
public class TokenGeneratorResult implements Serializable {
    private static final long serialVersionUID = -2345678901234567890L;

    private Map<String, String> tokens = new TreeMap<>();

    private Set<String> invalidAttributes = new HashSet<>();

    private Set<String> blankTokensByRule = new HashSet<>();
}
