/**
 * Copyright (c) Truveta. All rights reserved.
 */
package com.truveta.opentoken.tokens;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import lombok.Getter;

/**
 * Represents the result of a token generation operation.
 * <p>
 * This class contains the generated tokens, the list of invalid attributes,
 * and the count of blank tokens generated by rule.
 * </p>
 */
@Getter
public class TokenGeneratorResult implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * Map of generated tokens where keys are token identifiers (e.g., "T1", "T2")
     * and values are the generated token strings.
     * <p>
     * Uses TreeMap to maintain sorted order of token identifiers.
     * </p>
     */
    private Map<String, String> tokens = new TreeMap<>();

    /**
     * Set of attribute names that failed validation during token generation.
     * <p>
     * Contains the names of attributes that were invalid and could not be
     * processed for token generation.
     * </p>
     */
    private Set<String> invalidAttributes = new HashSet<>();

    /**
     * Set of token/rule identifiers that resulted in blank tokens.
     * <p>
     * A blank token occurs when required attributes are missing or invalid,
     * preventing the generation of a valid token for that rule.
     * </p>
     */
    private Set<String> blankTokensByRule = new HashSet<>();
}
