[project]
name = "openlinktoken-core-ai"
version = "2.2.0"
requires-python = ">=3.10"
dynamic = [
  "authors",
  "description",
  "optional-dependencies",
  "readme",
  "urls",
]
dependencies = [
  "openlinktoken==2.2.0",
  "numpy==1.26.4; python_version < '3.14'",
  "numpy==2.3.3; python_version >= '3.14'",
  "onnxruntime-gpu[cuda,cudnn]==1.23.2; platform_system == 'Linux' and platform_machine == 'x86_64' and python_version < '3.11'",
  "onnxruntime-gpu[cuda,cudnn]==1.25.1; platform_system == 'Linux' and platform_machine == 'x86_64' and python_version >= '3.11'",
  "onnxruntime==1.23.2; (platform_system != 'Linux' or platform_machine != 'x86_64') and python_version < '3.11'",
  "onnxruntime==1.25.1; (platform_system != 'Linux' or platform_machine != 'x86_64') and python_version >= '3.11'",
  "tokenizers==0.23.1",
]

[project.entry-points."openlinktoken.inference_providers"]
ml1 = "openlinktoken.core.ai.tokens.ml1_onnx_signature_provider:ML1OnnxSignatureProvider"

[project.entry-points."openlinktoken.tokens.definitions"]
ml1_token = "openlinktoken.core.ai.tokens.ml1_token:ML1Token"

[build-system]
requires = ["setuptools==84.0.0", "wheel==0.47.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/main"]

[tool.pytest.ini_options]
pythonpath = ["src/main", "src/test", "../../openlinktoken/src/main"]
testpaths = ["src/test"]
