name: "Setup Toolchain"
description: "Install shared Java and/or Python toolchains with caching"
inputs:
  java-version:
    description: "Version string passed to actions/setup-java"
    required: false
    default: "21"
  java-distribution:
    description: "Distribution for actions/setup-java"
    required: false
    default: "corretto"
  java-cache:
    description: "Cache strategy for actions/setup-java"
    required: false
    default: "maven"
  python-version:
    description: "Python version to install (omit to skip)"
    required: false
    default: ""
  python-cache:
    description: "Cache strategy for actions/setup-python"
    required: false
    default: "pip"
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      if: inputs.java-version != ''
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: ${{ inputs.java-cache }}

    - name: Set up Python
      if: inputs.python-version != ''
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.python-cache }}
