name: Interoperability Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  interoperability-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"
          cache: maven

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip

      - name: Install Python Dependencies
        run: |
          cd lib/python
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f dev-requirements.txt ]; then
            pip install -r dev-requirements.txt
          fi

      - name: Install Interoperability Test Dependencies
        run: |
          cd tools
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Build Java Application
        run: |
          cd lib/java
          mvn clean package -DskipTests
          echo "✅ Java JAR built successfully"

      - name: Run Interoperability Tests
        run: |
          echo "🔄 Running Interoperability Tests..."
          echo "Java Version: $(java -version 2>&1 | head -1)"
          echo "Python Version: $(python --version)"

          cd tools/interoperability
          python java_python_interoperability_test.py
          echo "✅ Interoperability tests completed successfully"
        env:
          PYTHONPATH: ${{ github.workspace }}/lib/python/src/main

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: interoperability-test-results
          path: |
            /tmp/*output*.csv
            /tmp/*decrypted*.csv
            tools/interoperability/*.log
          retention-days: 7

      - name: Report Results
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "## ✅ Interoperability Tests Passed! 🎉" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Key Validations Completed:**" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Java implementation generates tokens successfully" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Python implementation generates tokens successfully" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Both implementations produce identical encrypted tokens" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Decrypted tokens are identical between implementations" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Environment:** Java 11 + Python 3.9 on Ubuntu Latest" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ❌ Interoperability Tests Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The Java and Python implementations are not producing identical results." >> $GITHUB_STEP_SUMMARY
            echo "Check the job logs and uploaded artifacts for detailed comparison results." >> $GITHUB_STEP_SUMMARY
          fi
